---
- name: Install entropy service
  kewlfft.aur.aur:
    name:
      - rng-tools
      - opensc

- name: Enable entropy service
  become: yes
  ansible.builtin.systemd:
    enabled: yes
    state: started
    name: rngd
