- name: Install gpsd
  become: yes
  pacman:
    name:
      - gpsd

- name: Enable gpsd service
  become: yes
  systemd:
    enabled: yes
    state: started
    name: gpsd


- name: Install Navigation Tools
  become: true
  become_user: aur_builder
  aur:
    name:
      - stellarium
      # - opencpn
