- name: Install hyprland core tools
  kewlfft.aur.aur:
    name:
      - hypridle
      - hyprland
      - hyprland-qtutils
      - hyprlock
      - hyprpaper
      - hyprpicker
      - hyprpolkitagent
      - hyprsysteminfo
      - kitty
      - qt6-wayland
      - sddm
      - uwsm
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-hyprland
      - noto-fonts
      - ttf-nerd-fonts
      - grim
      - slurp
      - wofi
      - wl-clipboard
    state: present

- name: Install hyprpanel and its dependencies
  kewlfft.aur.aur:
    name:
      - ags-hyprpanel-git
      - aylurs-gtk-shell-git
      - bluez
      - bluez-utils
      - python-dbus
      - brightnessctl
      - btop
      - dart-sass
      - dart-sass
      - grimblast-git
      - gtksourceview3
      - gvfs
      - hyprpicker
      - hyprsunset
      - libgtop
      - libsoup3
      - matugen-bin
      - networkmanager
      - pacman-contrib
      - power-profiles-daemon
      - python
      - swww
      - upower
      - wf-recorder-git
      - wireplumber
    state: present

- name: Install screenshot tooling
  kewlfft.aur.aur:
    name:
      - jq
      - grim
      - slurp
      - wl-clipboard
      - libnotify
      - hyprpicker
      - satty
    state: present

- name: Enable and start polkit user services
  become: true
  become_user: "{{ carbs_user }}"
  ansible.builtin.systemd:
    name: hyprpolkitagent
    scope: user
    enabled: true
    state: started

- name: Enable and start SDDM (login manager)
  become: true
  ansible.builtin.systemd:
    name: sddm.service
    enabled: true
    state: started

- name: Enable and start NetworkManager
  become: true
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: true
    state: started

- name: Stop and disable dunst notification daemon
  become: true
  become_user: "{{ carbs_user }}"
  ansible.builtin.systemd:
    name: dunst
    scope: user
    enabled: false
    state: stopped
