- name: Install hyprland core tools
  kewlfft.aur.aur:
    name:
      - hypridle
      - hyprland
      - hyprland-qtutils
      - hyprlock
      - hyprpaper
      - hyprpicker
      - hyprpolkitagent
      - hyprsysteminfo
      - kitty
      - qt6-wayland
      - sddm
      - uwsm
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-hyprland
      - noto-fonts
      - ttf-nerd-fonts
      - grim
      - slurp

    state: present

- name: Enable and start polkit user services
  become: true
  become_user: "{{ carbs_user }}"
  ansible.builtin.systemd:
    name: hyprpolkitagent
    scope: user
    enabled: true
    state: started

- name: Enable and start SDDM (login manager)
  become: true
  ansible.builtin.systemd:
    name: sddm.service
    enabled: true
    state: started

- name: Enable and start NetworkManager
  become: true
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: true
    state: started

- name: Stop and disable dunst notification daemon
  become: true
  become_user: "{{ carbs_user }}"
  ansible.builtin.systemd:
    name: dunst
    scope: user
    enabled: false
    state: stopped
