- name: Ensure hyprland core tools are available
  kewlfft.aur.aur:
    name:
      - hypridle
      - hyprland
      - hyprland-qtutils
      - hyprlock
      - hyprpaper
      - hyprpicker
      - hyprpolkitagent
      - hyprsysteminfo
      - kitty
      - qt6-wayland
      - gdm
      - polkit
      - uwsm
      - noto-fonts
      - ttf-nerd-fonts
      - wofi
    state: present

- name: Ensure hyprpanel and its dependencies are available
  kewlfft.aur.aur:
    name:
      - ags-hyprpanel-git
      - aylurs-gtk-shell-git
      - bluez
      - bluez-utils
      - brightnessctl
      - btop
      - dart-sass
      - grimblast-git
      - gtksourceview3
      - gvfs
      - hyprpicker
      - hyprsunset
      - libgtop
      - libsoup3
      - matugen-bin
      - networkmanager
      - pacman-contrib
      - power-profiles-daemon
      - python
      - python-dbus
      - swww
      - upower
      - wf-recorder-git
      - wireplumber
    state: present

- name: Ensure screenshot tooling is available
  kewlfft.aur.aur:
    name:
      - jq
      - grim
      - slurp
      - wl-clipboard
      - libnotify
      - hyprpicker
      - satty
      - cliphist
      - wl-clip-persist
    state: present

# https://gist.github.com/brunoanc/2dea6ddf6974ba4e5d26c3139ffb7580
- name: Ensure screenshare tooling is available
  kewlfft.aur.aur:
    name:
      - grim
      - slurp
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-hyprland
    state: present

- name: Enable and start polkit user services
  become: true
  become_user: "{{ carbs_user }}"
  ansible.builtin.systemd:
    name: hyprpolkitagent
    scope: user
    enabled: true
    state: started

- name: Enable and start hypridle
  become: true
  become_user: "{{ carbs_user }}"
  ansible.builtin.systemd:
    name: hypridle
    scope: user
    enabled: true
    state: started

- name: Enable and start hyprpaper
  become: true
  become_user: "{{ carbs_user }}"
  ansible.builtin.systemd:
    name: hyprpaper
    scope: user
    enabled: true
    state: started

- name: Enable and start GDM (login manager)
  become: true
  ansible.builtin.systemd:
    name: gdm.service
    enabled: true
    state: started

- name: Enable and start NetworkManager
  become: true
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: true
    state: started

- name: Stop and disable dunst notification daemon
  become: true
  become_user: "{{ carbs_user }}"
  ansible.builtin.systemd:
    name: dunst
    scope: user
    enabled: false
    state: stopped

- name: Ensure dunst is uninstalled
  kewlfft.aur.aur:
    name:
      - dunst
    state: absent
