#!/bin/bash

docker-delete-stopped() {
    echo Deleting stopped containers
    docker rm $(docker ps -a -q)
}

docker-delete-untagged() {
    echo Deleting untagged images
    docker rmi $(docker images -q -f dangling=true)
}

docker-clean() {
    echo "Clean out untagged and stopped containers"
    docker-delete-stopped 
    docker-delete-untagged
}
alias dcl="docker-clean"


docker-attach () {
    docker start $1 && docker attach $1
}
alias da="docker-attach"

alias dka='docker kill $(docker ps -q)'
alias dps="docker ps"
alias drm="docker rm"

newbox() {
    docker run --name $1 --volumes-from=volume_container -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e BOX_NAME=$1 sthysel/toolbox
}
