#!/bin/bash

docker-build() {
    docker build -t $1 .
}
alias dbld="docker-build"

docker-remove-stopped() {
    echo Deleting stopped containers
    docker rm -v $(docker ps -a -f status=exited -q)
}

docker-remove-untagged() {
    images=rmi $(docker images --no-trunc | grep "<none>" | awk '{print $3}')
    if [[ $images ]]
    then
        echo "Deleting untagged images: $images"
        docker rmi $images 
    fi
}

docker-remove-unused() {
    echo "Removing unused docker images"
    images=($(docker images | awk '{print $1":"$2}'))
    containers=($(docker ps -a | awk '{print $2}'))
    
    containers_reg=" ${containers[*]} "
    remove=()
    
    for item in ${images[@]}; do
    if [[ ! $containers_reg =~ " $item " ]]; then
        remove+=($item)
    fi
    done
    
    remove_images=" ${remove[*]} "
    
    docker rmi ${remove_images}
}

docker-clean() {
    echo "Clean out untagged and stopped containers"
    docker-remove-stopped 
    docker-remove-untagged
}
alias dcl="docker-clean"


docker-attach() {
    docker start $1 && docker attach $1
}
alias da="docker-attach"

alias dka='docker kill $(docker ps -q)'
alias dps="docker ps"
alias drm="docker rm"

newbox() {
    echo "Spinning up $1"
    docker run --rm --name $1 -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v ${HOME}/.vimrc:/home/dev/.vimrc \
    -v ${HOME}/.vim:/home/dev/.vim \
    -v ${HOME}/.bashrc:/home/dev/.bashrc \
    -v ${HOME}/dotfiles:/home/dev/dotfiles \
    -e HOSTNAME=$1 sthysel/toolbox
}

ddoc() {
    echo "docker-build           dbld "
    echo "docker-remove-stoped        "
    echo "docker-remove-untaged       "
    echo "docker-clean           dcl  "
    echo "docker attach <name>   da   "
    echo "                       dka  "
    echo "                       dps  "
    echo "                       drm  "
    echo "newbox <name>               "
}
