#!/bin/bash

HERE=$(cd $(dirname $0) && pwd) 

echo "Installing from ${HERE} "

for file in "${HERE}"/*
do
    name="$(basename "$file" .md)"
    if ! [[ "apps install readme .gitignore" =~ ${name} || -d ${file}/.git ]]
    then
	    dotname=.${name}
	    ln -sfnv ${file#$HOME/} "${HOME}/${dotname}"
    fi
done

# vundle install for nvim
mkdir -p ~/.config/nvim/bundle/ 
git clone https://github.com/VundleVim/Vundle.vim.git ~/.config/nvim/bundle/Vundle.vim
ln -s ./vim/vimrc ~/.config/nvim/init.vim
# caps to escape
dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:escape']"
