- name: Install yazi and dependencies
  kewlfft.aur.aur:
    name:
      - yazi
      - file
      - ttf-nerd-fonts-symbols
      - ffmpeg
      - 7zip
      - jq
      - poppler
      - fd
      - ripgrep
      - zoxide
      - resvg
      - ImageMagick
      - mediainfo
      - perl-image-exiftool
      - ffmpegthumbnailer
    state: present

  become: yes
  become_user: aur_builder

- name: Install Yazi plugins
  ansible.builtin.shell: ya pack -l
  become: yes
  become_user: "{{ carbs_user }}"
