- name: Install yazi and dependencies
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - 7zip
      - fd
      - ffmpeg
      - ffmpegthumbnailer
      - file
      - imagemagick
      - jq
      - mediainfo
      - perl-image-exiftool
      - poppler
      - ripgrep
      - ttf-nerd-fonts-symbols
      - yazi
      - zoxide
    state: present

- name: Install Yazi plugins
  ansible.builtin.shell: ya pkg install
