---
- import_tasks: reflector.yml
- name: update the system
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install some common tools and core dependencies
  become: yes
  pacman:
    name:
      - ansible
      - archlinux-keyring
      - aspell-en
      - aspell-uk
      - base-devel
      - bat
      - curl
      - git
      - htop
      - imagemagick
      - lsd
      - make
      - neofetch
      - networkmanager
      - pacman-contrib
      - rsync
      - ranger
      - stow
      - trash-cli
      - wget
      - zsh
      - pyenv
    state: present

- import_tasks: aur.yml
- import_tasks: nobeep.yml
- import_tasks: users.yml
- import_tasks: entropy.yml
- import_tasks: usb.yml
