- name: No annoying beeps please
  become: yes
  copy:
    dest: "/etc/modprobe.d/nobeep.conf"
    content: | 
        # carbs
        # https://wiki.archlinux.org/index.php/PC_speaker 
        blacklist pcspkr
