- name: Main CARBS user
  become: yes
  user:
    name: "{{carbs_user}}"
    groups: wheel
    append: yes
    shell: /bin/zsh

- name: Backup CARBS user
  become: yes
  user:
    name: bro
    groups: wheel
    append: yes
