directory: /home/thys/apie/beets/music
library: /home/thys/apie/beets/data/musiclibrary.db

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: $albumartist/$album%aunique{}/$track $title
  comp: Compilations/$album%aunique{}/$track $title

plugins:
  - web
  - fetchart
  - embedart
  - lyrics
  - lastgenre
  - mbsync
  - chroma
  - thumbnails
  - duplicates
  - info
  - fromfilename

import:
  move: yes
  write: yes
  resume: no
  autotag: yes
  incremental: no
  format_item: '$albumartist - $album - $title'
  backend: ffmpeg
  log: beetslog.txt
  quiet_fallback: asis

ytimport:
  directory: /home/thys/apie/youtube
  auth_headers: /home/thys/apie/youtube/headers.txt
  import: true
  format: bestaudio/best


duplicates:
  keys: albumartist title album album_id
  action: keep

chroma:
  auto: true

ui:
  color: yes

embedart:
  ifempty: yes

musicbrainz:
  extra_tags: [year, catalognum, country, media, label]

match:
  strong_rec_thresh: 0.25
  medium_rec_thresh: 0.20
  distance_weights:
    missing_tracks: 0.1
    unmatched_tracks: 0.5
  ignored: missing_tracks

# For files with useful filenames
fromfilename:
  auto: yes
