- name: Remove pulseAudio
  community.general.pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - jack
    state: absent
    force: yes
  become: yes

- name: Install pipewire and related audio tooling
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - pipewire
      - pipewire-utils
      - pipewire-audio
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - pipewire-jack        # Optional: JACK support
      - pipewire-bluetooth   # Optional: Bluetooth support
      - qpwgraph
      - helvum
      - coppwr

- name: Enable and start pipewire user services
  ansible.builtin.systemd:
    name: "{{ item }}"
    scope: user
    enabled: yes
    state: started
  become: true
  become_user: "{{ carbs_user }}"
  loop:
    - pipewire
    - pipewire-pulse
    - wireplumber

- name: Music and video players
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - mplayer
      - pavucontrol
      - pulsemixer
      - playerctl
      - mpv
    state: present

- name: MPD and clients
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - mpd
      - mpc
      - ncmpcpp
    state: present
