- name: Remove PulseAudio
  community.general.pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - jack
    state: absent
    force: yes
  become: yes

- name: Install PipeWire and related audio packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - pipewire
      - pipewire-audio
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - pipewire-jack        # Optional: JACK support
      - pipewire-bluetooth   # Optional: Bluetooth support

- name: Enable and start PipeWire user services
  ansible.builtin.systemd:
    name: "{{ item }}"
    scope: user
    enabled: yes
    state: started
  become: true
  become_user: "{{ carbs_user }}"
  loop:
    - pipewire
    - pipewire-pulse
    - wireplumber
