- name: Remove pulseAudio
  community.general.pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - jack
    state: absent
    force: yes
  become: yes

- name: Install pipewire and related audio tooling
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - pipewire
      - pipewire-utils
      - pipewire-audio
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - pipewire-jack
      - pipewire-bluetooth
      - qpwgraph
      - helvum
      - coppwr

- name: Enable and start pipewire user services
  ansible.builtin.systemd:
    name: "{{ item }}"
    scope: user
    enabled: yes
    state: started
  become: true
  become_user: "{{ carbs_user }}"
  loop:
    - pipewire
    - pipewire-pulse
    - wireplumber

- name: Music and video players
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - mplayer
      - pavucontrol
      - pulsemixer
      - playerctl
      - mpv
    state: present

- name: MPD and clients
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - mpd
      - mpc
      - rmpc
      - ncmpcpp
    state: present

- name: Ensure MPD config and cache directories exist for "{{ carbs_user }}"
  become: true
  become_user: "{{ carbs_user }}"
  vars:
    xdg_config_home: "{{ lookup('env', 'XDG_CONFIG_HOME') | default('/home/' ~ carbs_user ~ '/.config', true) }}"
    xdg_cache_home: "{{ lookup('env', 'XDG_CACHE_HOME') | default('/home/' ~ carbs_user ~ '/.cache', true) }}"
  loop:
    - "{{ xdg_config_home }}/mpd/playlists"
    - "{{ xdg_cache_home }}/mpd/database"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ carbs_user }}"
    group: "{{ carbs_user }}"

- name: Enable and start media player daemon user service
  become: true
  become_user: "{{ carbs_user }}"
  ansible.builtin.systemd:
    name: mpd
    scope: user
    enabled: yes
    state: started
