- name: update the system
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install some common tools and core dependencies
  become: yes
  pacman:
    name:
      - archlinux-keyring
      - ansible
      - aspell-en
      - aspell-uk
      - base-devel
      - bat
      - curl
      - docker
      - git
      - htop
      - imagemagick
      - lsd
      - make
      - neofetch
      - networkmanager
      - pacman-contrib
      - rsync
      - stow
      - trash-cli
      - wget
      - xclip
      - xdotool
      - xsel
      - zsh
    state: present

- import_tasks: aur.yml
- import_tasks: python.yml
- import_tasks: editors.yml
- import_tasks: i3.yml
- import_tasks: fonts.yml
- import_tasks: music.yml
- import_tasks: video.yml
- import_tasks: nobeep.yml
- import_tasks: xps.yml
- import_tasks: multiscreens.yml
- import_tasks: docker.yml
- import_tasks: pandoc.yml
- import_tasks: users.yml
- import_tasks: entropy.yml
- import_tasks: usb.yml

