- name: Disk auto mounter, USB and hot-swapable SATA
  kewlfft.aur.aur:
    name:
      - udisks2
      - udiskie
    state: present

- name: Create polkit rules for udiskie mounting
  template:
    src: 50-udiskie.rules.j2
    dest: /etc/polkit-1/rules.d/50-udiskie.rules
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart polkit

- name: Add user to storage group
  ansible.builtin.user:
    name: "{{ carbs_user }}"
    groups: storage
    append: yes
  become: true

- name: Ensure systemd user directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
    mode: '0755'

- name: Deploy udiskie systemd user service file
  template:
    src: udiskie.service.j2
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/udiskie.service"
    mode: '0644'
  notify:
    - Reload systemd user daemon
    - Restart udiskie service

- name: Enable udiskie service
  systemd:
    name: udiskie.service
    enabled: true
    state: started
    scope: user
