#!/bin/sh

# i3blocks module for pacman upgrades.
# Displays number of upgradeable packages.
# Depends on pacman-contrib package
# When clicked, it will run an upgrade via pacman.

TERMINAL=kitty

help="📦
Left click to upgrade packages
Middle click to show upgradable packages
"

case $BLOCK_BUTTON in
	1) $TERMINAL -e ~/.config/i3blocks/popupgrade ;;
	2) notify-send "$(/usr/bin/pacman -Qu)" ;;
	3) pgrep -x dunst >/dev/null && notify-send "$help"  ;;
esac

checkupdates | wc -l | sed -e "s/^0$//g"
