#!/bin/sh

REPORT=~/.weatherreport
TERMINAL=kitty

### If location isn't automatically detected set this
location="Roleystone"

help="🌈
Click for wttr.in forecast.
☔ Chance of rain
❄ Daily low
🌞 Daily high
"

case $BLOCK_BUTTON in
    1) $TERMINAL -e less -R -S ${REPORT} ;;
    3) pgrep -x dunst >/dev/null && notify-send "$help" ;;
esac

[ "$location" != "" ] && location="$location+"

# ping me to see if there is a network, if not don't bother
my_ip="$(ip r | grep default | tail -1 | cut -d ' ' -f 3)"
ping -q -w 1 -c 1 $my_ip >/dev/null || exit

# fetch weather
curl -s wttr.in/$location > ${REPORT}

printf "%s" "$(sed '16q;d' ${REPORT} | grep -wo "[0-9]*%" | sort -n | sed -e '$!d' | sed -e "s/^/☔ /g" | tr -d '\n')"

sed '13q;d' ${REPORT} | grep -o "m\\(-\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print " ❄️",$1 "°","🌞",$2 "°"}'

