- name: Remove i3-wm
  become: true
  pacman:
    name:
      - i3-wm
    state: removed

- name: Install i3 and things it needs
  become: true
  pacman:
    name:
      - acpi
      - bc
      - calcurse
      - conky
      - dunst
      - feh
      - flameshot
      - i3-gaps
      - i3blocks
      - i3status
      - kitty
      - lightdm
      - lightdm-gtk-greeter
      - numlockx
      - openvpn
      - picom
      - rofi
      - sysstat
      - xorg-apps
      - xorg-server
      - xorg-xinit
    state: present
