import? x'$JUST_IIOT_PATH'

# Default recipe to verify global justfile is loaded
[private]
default:
    @echo "Global justfile loaded from ~/.config/just/justfile"

# Update system packages with yay
[doc('Update system packages with yay -Syu')]
update:
    yay -Syu
