#!/bin/bash

# converts a large avi video to a compressed low-res mkv video

IN=$1
OUT=$(sed "s/avi/mp4/" <<< $1)
echo "$IN -> $OUT"

ffmpeg -i $IN -acodec libfaac -b:a 128k -vcodec mpeg4 -b:v 1200k -flags +aic+mv4 $OUT
