- name: Install and enable docker
  become: yes
  pacman:
    name:
      - docker
      - docker-compose

- name: Enable docker
  become: yes
  systemd:
    enabled: yes
    state: started
    name: docker
