---
- hosts: all
  vars:
    username: thys
  tasks:
    - name: update the system
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install some common tools
      become: yes
      pacman:
        name:
          - ansible
          - curl
          - docker
          - git
          - htop
          - lsd
          - rsync
          - stow
          - wget
          - neofetch
          - mplayer
        state: present

    - name: Install Python dev env
      become: yes
      pacman:
        name:
          - python
          - python-pip
          - python-virtualenvwrapper
        state: present

    - name: Install code tools
      become: yes
      pacman:
        name:
          - neovim
          - emacs
        state: present

    - name: Install i3 and things it needs
      become: yes
      pacman:
        name:
          - acpi 
          - bc 
          - compton
          - conky
          - i3-gaps
          - i3blocks
          - i3blocks 
          - kitty
          - lightdm 
          - lightdm-gtk-greeter
          - numlockx
          - openvpn
          - rofi
          - sysstat
          - xorg-apps 
          - xorg-server 
          - xorg-xinit 
          - flameshot
        state: present

    - name: Music and Video
      become: yes
      pacman:
        name:
          - mplayer
          - pavucontrol
          - playerctl
          - mpd
          # terminal interface for mpd
          - mpc
          - mpv
          - ncmpcpp
          

    - name: Sweet fonts
      become: yes
      pacman:
        name:
          - ttf-joypixels
          - noto-fonts 
          - terminus-font 
          - ttf-dejavu 
          - ttf-droid 
          - ttf-font-awesome
          - ttf-inconsolata 
          - ttf-liberation 
          - ttf-roboto 
          - ttf-ubuntu-font-family 
        state: present
