---
- name: Provision tv media center
  hosts: tv
  remote_user: thys
  become: true
  roles:
    - role: base
    - role: audio
      tags:
        - audio
    - role: fonts
      tags:
        - fonts
    - role: ssh
    - role: jellyfin
      tags:
        - jellyfin
        - media
    - role: cage-kiosk
      tags:
        - kiosk
