---
- name: Provision twinks
  hosts: twinks
  remote_user: thys
  become: true
  roles:
    - role: base
    - role: audio
      tags:
        - audio
    - role: spacemacs
      tags:
        - editor
        - dev
    - role: docker
      tags:
        - container
        - dev
    - role: hyprland
      tags:
        - hyprland
    - role: python-dev
      tags:
        - dev
        - python
    - role: ssh
