---
- name: Provision vive
  hosts: vive
  remote_user: thys
  become: true
  roles:
    - role: base
    - role: audio
      tags:
        - audio
    - role: spacemacs
      tags:
        - editor
        - dev
