#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# powerline
powerline-daemon -q
source /usr/share/powerline/bindings/zsh/powerline.zsh


# source all alias and function files in ${ALIAS_HOME} ending in .alias
ALIAS_HOME=${HOME}/dotfiles/alias.d 
if [ -d ${ALIAS_HOME} ]
then
  for a in $(find -L ${ALIAS_HOME} -type f -name "*.alias")
  do
    source $a
  done
fi

# python --user
export PATH=${PATH}:${HOME}/.local/bin
